server:
  port: 7777
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /@project.artifactId@

# elasticsearch
# 9200端口是用来让HTTP REST API来访问ElasticSearch，而9300端口是传输层监听的默认端口
#spring:
#  data:
#    elasticsearch:
#      cluster-name: my-application
#      cluster-nodes: 10.20.4.66:9300